lobbyDuration: 20
gameDuration: 300
finishDuration: 20
debugEnabled: true
minimumPlayers: 2
palettes:
-  genelectrovise:
   - DIAMOND_BLOCK
   - JUKEBOX
   - CARVED_PUMPKIN
   - GOLD_ORE
externalLobbyLocation:
   worldName: world
   x: 0
   y: 100
   z: 0