lobbyDuration: 20
gameDuration: 300
debugEnabled: true
palettes:
-  genelectrovise:
   - DIAMOND_BLOCK
   - JUKEBOX
   - CARVED_PUMPKIN
   - GOLD_ORE
games:
   example:
      worldName: world
      x: 0
      y: 60
      z: 0
      palette: genelectrovise