main: net.clicksminuteper.HideAndSeek.main.HideAndSeek
name: HideAndSeek
version: SNAPSHOT-2.0.0
author: GenElectrovise
description: A Plugin for running Hide And Seek games on your server.
api-version: 1.15
depend: [Citizens, LibsDisguises, ProtocolLib]
commands:
   newgame:
      description: Creates a new HideAndSeek Game at the given coords
      usage: newgame X Y Z PALETTE
      permission: hideandseek.newgame
      permission-message: You don't have the hideandseek.newgame permission.
   join:
      description: Joins a HideAndSeek game
      usage: join --OR-- join X Y Z
      permission: hideandseek.join
      permission-message: You don't have the hideandseek.join permission.
   destroygame:
      description: Destroys a HideAndSeek game
      usage: destroy X Y Z
      permission: hideandseek.destroygame
      permission-message: You don't have the hideandseek.destroygame permission.
   listgames:
      description: Lists the active HideAndSeek games
      usage: listgames
      permission: hideandseek.listgames
      permission-message: You don't have the hideandseek.listgames permission.
   nitwit:
      description: Spawns a HideAndSeek nitwit at the calling player's location.
      usage: nitwit
      permission: hideandseek.nitwit
      permission-message: You don't have the hideandseek.nitwit permission.