main: net.clicksminuteper.HideAndSeek.main.HideAndSeek
name: HideAndSeek
version: SNAPSHOT-0.0.1
author: GenElectrovise
description: A Plugin for running Hide And Seek games on your server.
api-version: 1.15
depend: [Citizens]
commands:
   hnstest:
      description: Tests HideAndSeek's disguising functionality
      usage: hnstest TARGET BLOCK
      permission: hideandseek.hnstest
      permission-message: You don't have the hideandseek.hnstest permission.
   newgame:
      description: Creates a new HideAndSeek Game at the given coords
      usage: newgame X Y Z PALETTE
      permission: hideandseek.newgame
      permission-message: You don't have the hideandseek.newgame permission.
   join:
      description: Joins a HideAndSeek game
      usage: join --OR-- join X Y Z
      permission: hideandseek.join
      permission-message: You don't have the hideandseek.join permission.
   destroygame:
      description: Destroys a HideAndSeek game
      usage: destroy X Y Z
      permission: hideandseek.destroygame
      permission-message: You don't have the hideandseek.destroygame permission.